### PR TITLE
Add functional test and fix container usage

### LINKED ISSUE #471: The "security.token_storage" service or alias has been removed or inlined when the container was compiled.
### Environment
Docker image: php:8.0.13-apache
Symfony 6.0.2
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/entity-audit-bundle 1.6.1 1.6.1 Audit for Doctrine Entities
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v6.0.1  v6.0.1  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v6.0.1  v6.0.1  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                      v6.0.2  v6.0.2  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v3.0.0  v3.0.0  Generic abstractions related to caching
symfony/config                     v6.0.2  v6.0.2  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v6.0.2  v6.0.2  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.0.2  v6.0.2  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v6.0.2  v6.0.2  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/dependency-injection       v6.0.2  v6.0.2  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.0.0  v3.0.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v6.0.2  v6.0.2  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v6.0.2  v6.0.2  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v6.0.2  v6.0.2  Registers environment variables from a .env file
symfony/error-handler              v6.0.2  v6.0.2  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.0.2  v6.0.2  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.0.0  v3.0.0  Generic abstractions related to dispatching event
symfony/expression-language        v6.0.1  v6.0.1  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v6.0.0  v6.0.0  Provides basic utilities for the filesystem
symfony/finder                     v6.0.2  v6.0.2  Finds files and directories via an intuitive fluent interface
symfony/flex                       v2.0.1  v2.0.1  Composer plugin for Symfony
symfony/form                       v6.0.2  v6.0.2  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v6.0.2  v6.0.2  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v6.0.2  v6.0.2  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v3.0.0  v3.0.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v6.0.2  v6.0.2  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v6.0.2  v6.0.2  Provides a structured process for converting a Request into a Response
symfony/intl                       v6.0.1  v6.0.1  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v6.0.2  v6.0.2  Helps sending emails
symfony/maker-bundle               v1.36.4 v1.36.4 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v6.0.2  v6.0.2  Allows manipulating MIME messages
symfony/monolog-bridge             v6.0.1  v6.0.1  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.1  v3.7.1  Symfony MonologBundle
symfony/notifier                   v6.0.2  v6.0.2  Sends notifications via one or more channels (email, SMS, ...)
symfony/options-resolver           v6.0.0  v6.0.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v6.0.2  v6.0.2  Provides password hashing utilities
symfony/phpunit-bridge             v6.0.0  v6.0.0  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.24.0 v1.24.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.24.0 v1.24.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.24.0 v1.24.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.24.0 v1.24.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.24.0 v1.24.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.24.0 v1.24.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.24.0 v1.24.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.24.0 v1.24.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/polyfill-uuid              v1.24.0 v1.24.0 Symfony polyfill for uuid functions
symfony/process                    v6.0.2  v6.0.2  Executes commands in sub-processes
symfony/property-access            v6.0.2  v6.0.2  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v6.0.2  v6.0.2  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v6.0.2  v6.0.2  Provides integration for ProxyManager with various Symfony components
symfony/routing                    v6.0.1  v6.0.1  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v6.0.0  v6.0.0  Enables decoupling PHP applications from global state
symfony/security-bundle            v6.0.2  v6.0.2  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v6.0.2  v6.0.2  Symfony Security Component - Core Library
symfony/security-csrf              v6.0.1  v6.0.1  Symfony Security Component - CSRF Library
symfony/security-http              v6.0.2  v6.0.2  Symfony Security Component - HTTP Integration
symfony/serializer                 v6.0.2  v6.0.2  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v3.0.0  v3.0.0  Generic abstractions related to writing services
symfony/stopwatch                  v6.0.0  v6.0.0  Provides a way to profile code
symfony/string                     v6.0.2  v6.0.2  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v6.0.2  v6.0.2  Provides tools to internationalize your application
symfony/translation-contracts      v3.0.0  v3.0.0  Generic abstractions related to translation
symfony/twig-bridge                v6.0.2  v6.0.2  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v6.0.1  v6.0.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/uid                        v6.0.2  v6.0.2  Provides an object-oriented API to generate and represent UIDs
symfony/ux-turbo                   v2.0.1  v2.0.1  Hotwire Turbo integration for Symfony
symfony/validator                  v6.0.2  v6.0.2  Provides tools to validate values
symfony/var-dumper                 v6.0.2  v6.0.2  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.0.0  v6.0.0  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v6.0.1  v6.0.1  Manages links between resources
symfony/web-profiler-bundle        v6.0.2  v6.0.2  Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle      v1.13.2 v1.13.2 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v6.0.2  v6.0.2  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.0.13 (cli) (built: Dec  2 2021 13:29:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

## Subject
Saving does return error. I am using this bundle together with Doctrine extensions Gedmo Translatable and Blamable.

## Steps to reproduce
Create entity object and save it by calling Doctrine persist and flush method.

## Expected results
Succesful saving without returning an error.

## Actual results
````
In Container.php line 235:

The "security.token_storage" service or alias has been removed or inlined w
hen the container was compiled. You should either make it public, or stop u
sing the container directly and use dependency injection instead.
````

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

I was trying to add a functional test and in the way some issues came up.

I am targeting this branch, because this is BC.

Closes #471.

## Changelog

```markdown
### Deprecated
- Constructing `TokenStorageUsernameCallable` with an instance of `Container`, use an instance of `TokenStorageInterface` instead
### Fixed
- Fixed service id of `ViewEntityAction`
### Removed
- Support for `doctrine/orm` < 1.12.8
```

### CODE REVIEW

File: tests/custom_bootstrap.php [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+$application->run($input, new NullOutput());
+
+$input = new ArrayInput([
+    'command' => 'doctrine:schema:create',
+]);
+$application->run($input, new NullOutput());
+
+$input = new ArrayInput([
+    'command' => 'doctrine:fixtures:load',
+    '--no-interaction' => false,
```
Comment (jordisala1991) [inline tests/custom_bootstrap.php]: why false?

File: tests/Functional/SmokeTest.php [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+namespace SimpleThings\EntityAudit\Tests\Functional;
+
+use PHPUnit\Framework\TestCase;
+use SimpleThings\EntityAudit\Tests\App\AppKernel;
+use SimpleThings\EntityAudit\Tests\App\Entity\User;
+use Symfony\Bundle\FrameworkBundle\KernelBrowser;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+
+final class SmokeTest extends TestCase
```
Comment (jordisala1991) [inline tests/Functional/SmokeTest.php]: Why dont you use Webtestcase?

File: tests/custom_bootstrap.php (hunk 1 above)
Comment (franmomu) [reply tests/custom_bootstrap.php]: I didn't pay attention, copied from somewhere else, since it's an option maybe that value is not used.

File: tests/Functional/SmokeTest.php (hunk 2 above)
Comment (franmomu) [reply tests/Functional/SmokeTest.php]: changed

**Review by VincentLanglet — APPROVED** [review]

File: tests/App/AppKernel.php [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+/*
+ * This file is part of the Sonata Project package.
+ *
+ * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace SimpleThings\EntityAudit\Tests\App;
```
Comment (jordisala1991) [inline tests/App/AppKernel.php:14]: This would be problematic for dev-kit, it wont be able to generate the correct namespace. It will try to use Sonata when adding the console lints.

Since this is tests files, we could change the test namespace to use Sonata and it would fix this problem. Or you will need to introduce an if in the code for this case

Comment (franmomu) [reply tests/App/AppKernel.php:14]: I've removed the container test in dev-kit https://github.com/sonata-project/dev-kit/pull/1880 in the meantime. 

Maybe the console bin file could read the `AppKernel` class name from an external variable or be able to configure it in dev-kit using as default name the current behaviour.

Comment (VincentLanglet) [reply tests/App/AppKernel.php:14]: Our goal was stop remove the option from the dev-kit later, so it would be nice to not rely on a name provided by the devkit.

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @franmomu
