### PR TITLE
Fix: Compare Action route

### LINKED ISSUE #405: Compare Revision (`CompareAction`) route not working
### Environment

Mac OS 10.14.6
PHP FPM 7.4.16
nginx 1.21.1
Symfony 4.4

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/entity-audit-bundle 1.3.2 1.3.2 Audit for Doctrine Entities
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/apache-pack                v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v4.4.20 v5.3.2  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v4.4.20 v5.3.0  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                      v4.4.20 v5.3.3  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.2.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v4.4.20 v5.3.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v4.4.20 v5.3.2  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v4.4.20 v5.3.0  Converts CSS selectors to XPath expressions
symfony/debug                      v4.4.20 v4.4.25 Provides tools to ease debugging PHP code
symfony/debug-bundle               v4.4.20 v5.3.0  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/debug-pack                 v1.0.9  v1.0.9  A debug pack for Symfony projects
symfony/dependency-injection       v4.4.20 v5.3.3  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.2.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.20 v5.3.3  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v4.4.20 v5.3.0  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v4.4.20 v5.3.0  Registers environment variables from a .env file
symfony/error-handler              v4.4.20 v5.3.3  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v4.4.20 v5.3.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v1.1.9  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.20 v5.3.0  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v4.4.20 v5.3.3  Provides basic utilities for the filesystem
symfony/finder                     v4.4.20 v5.3.0  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.12.2 v1.13.3 Composer plugin for Symfony
symfony/form                       v4.4.20 v5.3.3  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.20 v5.3.3  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v4.4.20 v5.3.3  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.3.1  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.20 v5.3.3  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v4.4.20 v5.3.3  Provides a structured process for converting a Request into a Response
symfony/inflector                  v4.4.20 v5.3.0  Converts words between their singular and plural forms (English only)
Package symfony/inflector is abandoned, you should avoid using it. Use use `EnglishInflector` from the String component instead instead.
symfony/intl                       v4.4.20 v5.3.0  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v4.4.20 v5.3.3  Helps sending emails
symfony/mailgun-mailer             v4.4.20 v5.3.0  Symfony Mailgun Mailer Bridge
symfony/maker-bundle               v1.29.1 v1.33.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v4.4.20 v5.3.3  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v4.4.20 v5.3.2  Allows manipulating MIME messages
symfony/monolog-bridge             v4.4.20 v5.3.3  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.6.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v4.4.20 v5.3.0  Provides an improved replacement for the array_replace PHP function
symfony/orm-pack                   v2.1.0  v2.1.0  A pack for the Doctrine ORM
symfony/phpunit-bridge             v5.2.4  v5.3.3  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.22.1 v1.23.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.22.1 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.22.1 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.22.1 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.22.1 v1.23.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.22.1 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.22.1 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.22.1 v1.23.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-uuid              v1.22.1 v1.23.0 Symfony polyfill for uuid functions
symfony/process                    v4.4.20 v5.3.2  Executes commands in sub-processes
symfony/profiler-pack              v1.0.5  v1.0.5  A pack for the Symfony web profiler
symfony/property-access            v4.4.20 v5.3.0  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v4.4.20 v5.3.1  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v4.4.20 v5.3.0  Provides integration for ProxyManager with various Symfony components
symfony/routing                    v4.4.20 v5.3.0  Maps an HTTP request to a set of configuration variables
symfony/security-bundle            v4.4.20 v5.3.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v4.4.20 v5.3.3  Symfony Security Component - Core Library
symfony/security-csrf              v4.4.20 v5.3.3  Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.20 v5.3.0  Symfony Security Component - Guard
symfony/security-http              v4.4.20 v5.3.3  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.4.20 v5.3.2  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/serializer-pack            v1.0.4  v1.0.4  A pack for the Symfony serializer
symfony/service-contracts          v2.2.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.20 v5.3.0  Provides a way to profile code
symfony/string                     v5.2.4  v5.3.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/test-pack                  v1.0.7  v1.0.8  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                v4.4.20 v5.3.3  Provides tools to internationalize your application
symfony/translation-contracts      v2.3.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.20 v5.3.3  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v4.4.20 v5.3.3  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/uid                        v5.2.4  v5.3.3  Provides an object-oriented API to generate and represent UIDs
symfony/validator                  v4.4.20 v5.3.3  Provides tools to validate values
symfony/var-dumper                 v4.4.20 v5.3.3  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v4.4.20 v5.3.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v4.4.20 v5.3.3  Manages links between resources
symfony/web-profiler-bundle        v4.4.20 v5.3.2  Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle      v1.11.1 v1.12.0 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.4.20 v5.3.3  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.16 (cli) (built: Apr 25 2021 06:54:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

## Subject

When attempting to compare revisions on the `simple_things_entity_audit_compare` route (coming from the `simple_things_entity_audit_viewentity_detail` route), I get an exception.

## Minimal repository with the bug

...this is a fairly simple fix, do I need to do this?

## Steps to reproduce

I'd like to view the revisions of an entity which I've enabled the `EntityAuditBundle` for. I added a route:

```
simple_things_entity_audit:
    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing/audit.xml"
    prefix: /audit
```

I can visit that route and click on a revision. Then I can click on the class name which takes me to this url:

https://example.com/audit/viewent/App%5CEntity%5CExampleEntity/1/2

The list of revisions looks like this:

Screenshot 2021-07-09 at 16 09 07

## Expected results

When I click on `Compare Revisions` I expect to see a revisions comparison.

## Actual results

The following exception is thrown:

`Argument 4 passed to SimpleThings\EntityAudit\Action\CompareAction::__invoke() must be of the type int or null, string given`

Stack trace:

```
TypeError:
Argument 4 passed to SimpleThings\EntityAudit\Action\CompareAction::__invoke() must be of the type int, string given, called in /vendor/symfony/http-kernel/HttpKernel.php on line 158

  at vendor/sonata-project/entity-audit-bundle/src/Action/CompareAction.php:39
  at SimpleThings\EntityAudit\Action\CompareAction->__invoke(object(Request), 'App\\Entity\\ExampleEntity', '1', '', '')
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
  at require('~/site/public/index.php')
     (~/.composer/vendor/laravel/valet/server.php:214)   
```

### PR DESCRIPTION
**Pull request by BurningDog**
## Subject

This fixes the issue where a revision could not be viewing via the `CompareAction` route.

I am targeting the `1.x` branch because it's a bug fix which is backwards compatible.

Closes #405.

## Changelog

```markdown
### Fixed

- The CompareAction route is now working.
```

### CODE REVIEW

File: src/Action/CompareAction.php [hunk 1]
```diff
@@ -46,8 +46,7 @@ public function __invoke(Request $request, string $className, string $id, ?int $
             $newRev = $request->query->get('newRev');
         }
 
-        $ids = explode(',', $id);
-        $diff = $this->auditReader->diff($className, $ids, $oldRev, $newRev);
+        $diff = $this->auditReader->diff($className, $id, $oldRev, $newRev);
```
Comment (VincentLanglet) [inline src/Action/CompareAction.php:49]: Array are supposed to be supported https://github.com/sonata-project/EntityAuditBundle/blob/e38bb57ea321f59960fd38fe8f88050763524635/src/AuditReader.php#L617
and find support array too https://github.com/sonata-project/EntityAuditBundle/blob/e38bb57ea321f59960fd38fe8f88050763524635/src/AuditReader.php#L220

I would say we try to support something like `3,4,5`.

Do it mean this case is broken https://github.com/sonata-project/EntityAuditBundle/blob/e38bb57ea321f59960fd38fe8f88050763524635/src/AuditReader.php#L235 ?

@wbloszyk @phansys you're using this bundle, do you pass array/multiple ids some times ?

Comment (BurningDog) [reply src/Action/CompareAction.php:49]: If we pass `$ids` as an array to the `find()` function, then inside https://github.com/sonata-project/EntityAuditBundle/blob/e38bb57ea321f59960fd38fe8f88050763524635/src/AuditReader.php#L235-L237 the values are:

* `$idKeys = [0 => 0]`
* `$columnName = 0`

...which leads to https://github.com/sonata-project/EntityAuditBundle/blob/e38bb57ea321f59960fd38fe8f88050763524635/src/AuditReader.php#L246 being

`$whereSQL = "e.rev <= ? AND e.0 = ?"`

While I think the type of `$id` at https://github.com/sonata-project/EntityAuditBundle/blob/e38bb57ea321f59960fd38fe8f88050763524635/src/AuditReader.php#L220 is correct, I think for the `diff()` function at https://github.com/sonata-project/EntityAuditBundle/blob/e38bb57ea321f59960fd38fe8f88050763524635/src/AuditReader.php#L617 it should be `* @param int|string $id` - because I _think_ a diff is on a single object, by definition.

In that case, the new value becomes:

`$whereSQL = "e.rev <= ? AND e.id = ?"` which is correct.

Comment (BurningDog) [reply src/Action/CompareAction.php:49]: ...I've added this change into the PR, as `CompareAction` is the only place which calls the `diff()` function in the `AuditReader`.

**Review by VincentLanglet — APPROVED** [review]

File: src/Action/CompareAction.php (hunk 1 above)
Comment (phansys) [reply src/Action/CompareAction.php:49]: >@wbloszyk @phansys you're using this bundle, do you pass array/multiple ids some times ?

I'm not using composite ids with this bundle.
This issue was reported before. See #288, #331 #389.

**Comment by VincentLanglet** [comment]
@BurningDog Can you do the same for others actions like in PR https://github.com/sonata-project/EntityAuditBundle/pull/331/files ?

**Comment by BurningDog** [comment]
@VincentLanglet ok, done - I searched for all calls to the `find()` and `findRevisions()` functions to ensure that the passed `$id` is either an `int` or a `string`.

**Review by VincentLanglet — APPROVED** [review]

**Review by phansys — COMMENTED** [review]
Are these changes disallowing the possibility of using entities with composite ids?
If yes, I think we must add validations to prevent these entities to be marked as auditable from the beginning.

**Comment by VincentLanglet** [comment]
> Are these changes disallowing the possibility of using entities with composite ids?
> 
> If yes, I think we must add validations to prevent these entities to be marked as auditable from the beginning.

Composite ids can be used if you call directly the method of the AuditReader, but cannot be used with these actions.

I dont think it's specifically new since you cannot pass composite ids in a url. Can u ?

Imho if something should be added it would be better to create an issue about, in order to not delay this bugfix

**Comment by phansys** [comment]
>I dont think it's specifically new since you cannot pass composite ids in a url. Can u ?

Yes, by instance you can use this approach for the [ORM manager](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/a7b586cb54e092388c13d7afb51438dd42d84093/src/Model/ModelManager.php#L333-L335): "/app/entity/1~42/show".

>Imho if something should be added it would be better to create an issue about, in order to not delay this bugfix

I agree.

**Review by phansys — APPROVED** [review]

**Review by franmomu — APPROVED** [review]
